const test = require('node:test')
const assert = require('node:assert/strict')
const Sequelize = require('sequelize')
const { createBadges, renderBadges, badgeField } = require('../services/badges')
const { config } = require('../services/spooky/config')
async function fixture(t) {
  const sequelize = new Sequelize({ dialect: 'sqlite', storage: ':memory:', logging: false })
  t.after(() => sequelize.close())
  await require('../migrations/20261001000000-create-spooky-core').up(sequelize.getQueryInterface())
  await require('../migrations/20261001000003-create-permanent-badges').up(sequelize.getQueryInterface())
  const models = require('../services/spooky/models').defineSpookyModels(sequelize)
  const economy = require('../services/spooky/economy').createEconomy({ sequelize, models, configVersion: config.version, clock: () => new Date(config.startsAt) })
  const participants = require('../services/spooky/participants').createParticipants({ models, economy, event: { ...config, enabled: true } })
  const input = key => ({ eventId: config.eventId, guildId: 'guild', actorId: 'alice', interactionId: key, operationType: 'badge_test' })
  await participants.register(input('register'))
  const badges = createBadges({ sequelize })
  const collection = require('../services/spooky/collection').createCollection({ models, participants, badges, event: { ...config, enabled: true, duplicates: { ...config.duplicates, allowDuplicates: true } } })
  const grant = (key, position, fail = false) => economy.execute(input(key), async ctx => {
    const receipt = await collection.grantQuarter(ctx, 'alice', `sel_${position}`)
    if (fail) throw new Error('injected badge interruption')
    return receipt
  })
  return { sequelize, models, badges, grant }
}
test('completing a character awards once atomically, survives reconstruction and seasonal participant deletion', async t => {
  const f = await fixture(t)
  for (const position of ['tl','tr','bl']) await f.grant(position, position)
  assert.deepEqual(await f.badges.owned('guild', 'alice'), [])
  await assert.rejects(() => f.grant('final', 'br', true), /interruption/)
  assert.deepEqual(await f.badges.owned('guild', 'alice'), [])
  const final = await f.grant('final', 'br')
  assert.deepEqual(final.receipt.newlyAwardedBadges, ['spooky-2026:sel'])
  const duplicate = await f.grant('duplicate', 'br')
  assert.deepEqual(duplicate.receipt.newlyAwardedBadges, [])
  assert.deepEqual((await f.grant('final', 'br')).receipt, final.receipt)
  assert.equal(await f.models.Ledger.count({ where: { resource: 'badge:spooky-2026:sel' } }), 1)
  await f.models.Participant.destroy({ where: { userId: 'alice' } })
  assert.deepEqual(await createBadges({ sequelize: f.sequelize }).owned('guild', 'alice'), ['spooky-2026:sel'])
  assert.deepEqual(await f.badges.owned('other', 'alice'), [])
})

test('latest Spooky badge is guild-scoped, persistent, and defaults to Selene', async t => {
  const f = await fixture(t)
  assert.equal((await f.badges.latest('guild')).characterId, 'sel')
  const Ownership = f.sequelize.models.BadgeOwnership
  await Ownership.create({ guildId: 'guild', userId: 'alice', badgeId: 'spooky-2026:mrq', sourceEventId: config.eventId, awardedAt: new Date(config.startsAt) })
  await Ownership.create({ guildId: 'other', userId: 'bob', badgeId: 'spooky-2026:sel', sourceEventId: config.eventId, awardedAt: new Date(Date.parse(config.startsAt) + 2000) })
  assert.equal((await f.badges.latest('guild')).characterId, 'mrq')
  await Ownership.create({ guildId: 'guild', userId: 'bob', badgeId: 'spooky-2026:sel', sourceEventId: config.eventId, awardedAt: new Date(Date.parse(config.startsAt) + 1000) })
  assert.equal((await createBadges({ sequelize: f.sequelize }).latest('guild')).characterId, 'sel')
})
test('shared renderer distinguishes missing/earned badges and resolves only usable Selene server emoji', () => {
  const emoji = { name: 'spooky_selene_badge', id: '123456789012345678' }
  assert.equal(renderBadges([], [emoji]), '❔ ❔ ❔ ❔ ❔ ❔ ❔')
  assert.equal(renderBadges(['spooky-2026:sel'], [emoji]), '❔ ❔ ❔ ❔ ❔ ❔ <:spooky_selene_badge:123456789012345678>')
  assert.equal(renderBadges(['spooky-2026:had','spooky-2026:sel'], []), '🏅 ❔ ❔ ❔ ❔ ❔ 🏅')
  assert.ok(renderBadges(['spooky-2026:sel'], [{ ...emoji, available: false }]).endsWith('🏅'))
})
test('badge leaderboard and profile field use permanent ownership independent of seasonal registration', async t => {
  const f = await fixture(t)
  for (const position of ['tl','tr','bl','br']) await f.grant(position, position)
  const rows = await f.badges.leaders('guild')
  assert.equal(rows[0].userId, 'alice'); assert.equal(rows[0].badgeCount, 1)
  assert.deepEqual(await f.badges.leaders('guild', 1, []), [])
  assert.deepEqual(await f.badges.leaders('guild', 1, ['bob']), [])
  assert.equal((await f.badges.leaders('guild', 1, ['alice']))[0].userId, 'alice')
  assert.deepEqual(await f.badges.leaders('other'), [])
  await assert.rejects(() => f.badges.leaders('guild', 0), /page/)
  const field = await badgeField({ id: 'guild', emojis: { fetch: async () => new Map([['sel', { name: 'spooky_selene_badge', id: '123456789012345678' }]]) } }, 'alice', f.sequelize)
  assert.match(field.value, /spooky_selene_badge/); assert.match(field.value, /1\/7/)
  assert.deepEqual(require('../commands/Achievements/Badges').data.toJSON().options.map(option => option.name), ['view','leaderboard'])
})
