const test = require('node:test')
const assert = require('node:assert/strict')
const Sequelize = require('sequelize')
const defineUser = require('../Models/User/User')
const migration = require('../migrations/20261001000000-create-spooky-core')
const { defineSpookyModels } = require('../services/spooky/models')
const { createEconomy } = require('../services/spooky/economy')
const { createParticipants } = require('../services/spooky/participants')
const { createActions } = require('../services/spooky/actions')
const { createProgression } = require('../services/spooky/progression')
const { config } = require('../services/spooky/config')

async function fixture(t, { eligible = true, bank = 0, random = () => .2 } = {}) {
  const sequelize = new Sequelize({ dialect: 'sqlite', storage: ':memory:', logging: false })
  t.after(() => sequelize.close())
  const User = defineUser(sequelize, Sequelize.DataTypes); await User.sync()
  await migration.up(sequelize.getQueryInterface())
  const models = defineSpookyModels(sequelize), event = { ...config, enabled: true }
  const economy = createEconomy({ sequelize, models, configVersion: event.version, clock: () => new Date(event.startsAt) })
  const participants = createParticipants({ models, economy, event })
  const progression = createProgression({ User, models, event, isUnwanted: () => eligible })
  const handlers = progression.wrapHandlers({ sweet_tooth: async () => ({ roleQueued: true }), lost_candy: async () => ({ noEffect: 'lost' }),
    steal_candy: async () => ({ stolen: 1 }), curse_distribute_two: async () => ({ deliveredCandy: 2 }), standard_gift: async () => ({ noEffect: 'no_recipient' }) })
  const actions = createActions({ models, participants, economy, event, handlers, random, getCurseState: () => false })
  const input = key => ({ eventId: event.eventId, guildId: 'guild', actorId: 'alice', interactionId: key, action: 'treat' })
  await participants.register(input('register'))
  const user = await User.create({ user_id: 'alice', user_name: 'Alice', bank, fate_points: 99 })
  const run = (key, fn) => economy.execute({ ...input(key), operationType: 'progression_test' }, fn)
  return { User, models, economy, event, participants, progression, actions, user, input, run }
}

test('configured host stays last and unranked across pages without displacing other players or winning', async t => {
  const f = await fixture(t), event = { ...f.event, competition: { nonCompetitiveUserIds: ['alice'] } }
  await f.run('host-high-score', ctx => f.progression.prestige(ctx, { actorId: 'alice', action: 'treat', outcome: 'sweet_tooth' }, { crownWon: true }))
  for (let index = 0; index < 11; index++) {
    const userId = `member${index}`
    await f.participants.register({ ...f.input(`reg-${userId}`), actorId: userId })
    await f.User.create({ user_id: userId, user_name: userId })
    await f.run(`score-${userId}`, ctx => f.progression.prestige(ctx, { actorId: userId, action: 'treat', outcome: 'standard_gift' }, {}))
  }
  const read = require('../services/spooky/leaderboard').createLeaderboard({ models: f.models, economy: f.economy, User: f.User, event })
  const scope = { eventId: event.eventId, guildId: 'guild' }
  const first = await read(scope), last = await read(scope, 2)
  assert.equal(first.length, 10); assert.ok(first.every(row => row.userId !== 'alice' && row.rank === 1))
  assert.equal(last.at(-1).userId, 'alice'); assert.equal(last.at(-1).rank, null); assert.equal(last.at(-1).nonCompetitive, true)
  assert.equal((await f.models.Participant.findOne({ where: { userId: 'alice' } })).treatPrestige, 12)
  const closingEconomy = createEconomy({ sequelize: f.User.sequelize, models: f.models, clock: () => new Date(event.endsAt) })
  const snapshots = require('../services/spooky/winner-snapshot').createWinnerSnapshot({ models: f.models, event })
  const frozen = await closingEconomy.execute({ ...scope, actorId: 'system', workerKey: 'host-proof', operationType: 'test' }, snapshots.freeze)
  const operation = await f.models.Operation.findByPk(frozen.receipt.operationId)
  assert.equal(operation.receipt.tracks.overall.entrants.some(row => row.userId === 'alice'), false)
  assert.equal(operation.receipt.tracks.overall.userIds.length, 11)
})

test('caller crown win credits five fate for any registered player, caps bank and adds ten prestige once', async t => {
  const f = await fixture(t, { eligible: false, bank: 98 })
  const handlers = f.progression.wrapHandlers({ sweet_tooth: async () => ({ crownWon: true, awardedUserId: 'alice' }) })
  const result = await f.run('new-crown', ctx => handlers.sweet_tooth(ctx, { actorId: 'alice', action: 'treat', outcome: 'sweet_tooth' }))
  assert.equal(result.receipt.fateBonus, 2); assert.equal((await f.user.reload()).bank, 100)
  assert.equal(result.receipt.prestige.delta, 12)
  assert.equal(result.receipt.bankBefore, 98)
  assert.equal(result.receipt.bank, 100)
  assert.equal(result.receipt.fatePoints, 99)
  await f.user.update({ bank: 50, fate_points: 60 })
  const replay = await f.run('new-crown', () => { throw new Error('no second award') })
  assert.equal(replay.receipt.bankBefore, 98)
  assert.equal(replay.receipt.bank, 100)
  assert.equal(replay.receipt.fatePoints, 99)
  assert.equal(replay.receipt.prestige.delta, 12)
  assert.equal((await f.models.Participant.findOne()).treatPrestige, 12)
})

test('successful Great Heist gets a five-point boost; failed heist cannot gain it', async t => {
  const f = await fixture(t)
  const plan = { actorId: 'alice', action: 'trick', outcome: 'great_heist' }
  const win = await f.run('heist-win', ctx => f.progression.prestige(ctx, plan, { stolen: 1 }))
  assert.equal(win.receipt.delta, 7)
  const miss = await f.run('heist-miss', ctx => f.progression.prestige(ctx, plan, { noEffect: 'no_funded_candy_target' }))
  assert.equal(miss.receipt.delta, 0)
})

test('Spooky leaderboard combines both tracks and returns ranks/badges without exposing hidden points', async t => {
  const f = await fixture(t)
  await f.run('rank-treat', ctx => f.progression.prestige(ctx, { actorId: 'alice', action: 'treat', outcome: 'sweet_tooth' }, { crownWon: true }))
  await f.run('rank-trick', ctx => f.progression.prestige(ctx, { actorId: 'alice', action: 'trick', outcome: 'great_heist' }, { stolen: 1 }))
  const read = require('../services/spooky/leaderboard').createLeaderboard({ models: f.models,
    economy: require('../services/spooky/economy').createEconomy({ sequelize: f.User.sequelize, models: f.models }), User: f.User })
  const rows = await read({ eventId: f.event.eventId, guildId: 'guild' })
  assert.equal(rows[0].rank, 1); assert.equal(rows[0].name, 'Alice')
  assert.equal(rows[0].score, undefined); assert.equal(rows[0].points, undefined)
  assert.deepEqual(rows[0].badges, [])
  assert.deepEqual(await read({ eventId: f.event.eventId, guildId: 'other' }), [])
})
test('Sweet Tooth credits one banked fate and treat prestige in the action transaction; concurrent replay once', async t => {
  const f = await fixture(t)
  const results = await Promise.all(Array.from({ length: 10 }, () => f.actions.execute(f.input('sweet'))))
  assert.equal(results[0].receipt.result.fateBonus, 1)
  assert.equal((await f.user.reload()).bank, 1)
  assert.equal(f.user.fate_points, 99)
  const participant = await f.models.Participant.findOne()
  assert.equal(participant.treatPrestige, 2)
  assert.equal(participant.trickPrestige, 0)
  assert.equal(participant.candy, 9)
  assert.equal(await f.models.Ledger.count({ where: { resource: 'bank' } }), 1)
})
test('non-Unwanted Sweet Tooth remains playable; full bank and near-cap are correct', async t => {
  const normal = await fixture(t, { eligible: false })
  assert.equal((await normal.actions.execute(normal.input('normal'))).receipt.result.fateBonus, 0)
  assert.equal((await normal.models.Participant.findOne()).treatPrestige, 2)
  const capped = await fixture(t, { bank: 100 })
  assert.equal((await capped.actions.execute(capped.input('cap'))).receipt.result.fateBonus, 0)
  const near = await fixture(t, { bank: 99 })
  assert.equal((await near.actions.execute(near.input('near'))).receipt.result.fateBonus, 1)
  assert.equal((await near.user.reload()).bank, 100)
})
test('only normal Sweet Tooth treats award fate; other outcomes and curse replacements do not', async t => {
  const f = await fixture(t)
  const wrapped = f.progression.wrapHandlers({ steal_candy: async () => ({ stolen: 1 }), curse_distribute_two: async () => ({ deliveredCandy: 2 }) })
  await f.run('trick', ctx => wrapped.steal_candy(ctx, { action: 'trick', outcome: 'steal_candy', actorId: 'alice', overridden: false }))
  await f.run('curse', ctx => wrapped.curse_distribute_two(ctx, { action: 'trick', outcome: 'curse_distribute_two', actorId: 'alice', overridden: true }))
  assert.equal((await f.user.reload()).bank, 0)
  assert.equal((await f.models.Participant.findOne()).trickPrestige, 3)
})
test('failure costs prestige, target no-effect scores zero, and bank/scoring failures roll back action candy', async t => {
  const lost = await fixture(t, { random: () => 0 })
  await lost.actions.execute(lost.input('lost'))
  assert.equal((await lost.models.Participant.findOne()).treatPrestige, -1)
  const empty = await fixture(t, { random: () => .6 })
  await empty.actions.execute(empty.input('empty'))
  assert.equal((await empty.models.Participant.findOne()).treatPrestige, 0)
  const missing = await fixture(t)
  await missing.user.destroy()
  await assert.rejects(() => missing.actions.execute(missing.input('missing')), /account/)
  assert.equal((await missing.models.Participant.findOne()).candy, 10)
  const provisional = createProgression({ ...lost, event: { ...lost.event, prestige: { ...config.prestige, status: 'provisional' } }, isUnwanted: () => true })
  await assert.rejects(() => lost.run('provisional', ctx => provisional.prestige(ctx, { action: 'treat', actorId: 'alice', outcome: 'standard_gift' }, {})), /provisional/)
})
test('ties share each track, a player may lead both, and inactive registrants do not win', async t => {
  const f = await fixture(t)
  await f.participants.register({ ...f.input('bob-register'), actorId: 'bob' })
  await f.participants.register({ ...f.input('idle-register'), actorId: 'idle' })
  for (const userId of ['alice','bob']) await f.run(`score-${userId}`, ctx => f.progression.prestige(ctx, { action: 'treat', actorId: userId, outcome: 'sweet_tooth' }, {}))
  await f.run('trick-score', ctx => f.progression.prestige(ctx, { action: 'trick', actorId: 'alice', outcome: 'steal_candy' }, {}))
  const leaders = await f.run('leaders', ctx => f.progression.leaders(ctx))
  assert.deepEqual(leaders.receipt.treat.userIds, ['alice','bob'])
  assert.deepEqual(leaders.receipt.trick.userIds, ['alice'])
})

test('Crown earns exact tenths on positive actions only; live rankings and frozen overall proof agree', async t => {
  const f = await fixture(t)
  await f.participants.register({ ...f.input('bob'), actorId: 'bob' })
  await f.User.create({ user_id: 'bob', user_name: 'Bob' })
  await f.run('hold', async ctx => {
    await ctx.record({ userId: 'alice', resource: 'crown_holder', delta: 0, metadata: { holderId: 'alice', roleId: 'sweet' } }); return {}
  })
  const handlers = f.progression.wrapHandlers({ standard_gift: async () => ({ deliveredCandy: 1 }),
    great_heist: async () => ({ stolen: 1 }), lost_candy: async () => ({ failure: 'lost_candy' }) })
  for (const userId of ['alice', 'bob']) await f.run(`gift-${userId}`, ctx => handlers.standard_gift(ctx, { action: 'treat', outcome: 'standard_gift', actorId: userId }))
  const aliceBonus = await f.models.Ledger.findOne({ where: { resource: 'crownPrestigeTenths' } })
  assert.equal(aliceBonus.delta, 2)
  const ranked = await require('../services/spooky/leaderboard').createLeaderboard({ models: f.models, economy: f.economy, User: f.User })({ eventId: config.eventId, guildId: 'guild' })
  assert.deepEqual(ranked.map(row => [row.userId, row.rank]), [['alice', 1], ['bob', 2]])
  const eligibleRanks = await require('../services/spooky/leaderboard').createLeaderboard({ models: f.models,
    economy: f.economy, User: f.User, eligibleUserIds: new Set(['bob']) })({ eventId: config.eventId, guildId: 'guild' })
  assert.deepEqual(eligibleRanks.map(row => [row.userId, row.rank]), [['bob', 1]])
  await f.run('heist-with-crown', ctx => handlers.great_heist(ctx, { action: 'trick', outcome: 'great_heist', actorId: 'alice' }))
  await f.run('loss-with-crown', ctx => handlers.lost_candy(ctx, { action: 'treat', outcome: 'lost_candy', actorId: 'alice' }))
  assert.equal(await f.models.Ledger.sum('delta', { where: { resource: 'crownPrestigeTenths' } }), 9)
  const snapshot = require('../services/spooky/winner-snapshot').createWinnerSnapshot({ models: f.models, event: f.event })
  await f.run('freeze', ctx => snapshot.freeze({ ...ctx, now: new Date(config.endsAt) }))
  const proof = (await f.models.Operation.findByPk(require('../services/spooky/winner-snapshot').snapshotOperationId(config.eventId, 'guild'))).receipt
  assert.equal(proof.tracks.overall.score, 8.9)
  assert.equal(proof.tracks.overall.entrants[0].scoreTenths, 89)
  assert.deepEqual(proof.tracks.overall.userIds, ['alice'])
  await f.run('reuse-proof', ctx => snapshot.freeze({ ...ctx, now: new Date(config.endsAt) }))
})
