const test = require('node:test')
const assert = require('node:assert/strict')
const Sequelize = require('sequelize')
const migration = require('../migrations/20261001000000-create-spooky-core')
const { defineSpookyModels } = require('../services/spooky/models')
const { createEconomy } = require('../services/spooky/economy')
const { createParticipants } = require('../services/spooky/participants')
const { createCollection } = require('../services/spooky/collection')
const { createActions } = require('../services/spooky/actions')
const { createTheft, randomTargets } = require('../services/spooky/theft')
const { config } = require('../services/spooky/config')

async function fixture(t, members = [], options = {}) {
  const sequelize = new Sequelize({ dialect: 'sqlite', storage: ':memory:', logging: false })
  t.after(() => sequelize.close())
  await migration.up(sequelize.getQueryInterface())
  const models = defineSpookyModels(sequelize), event = { ...config, enabled: true }
  let now = new Date(config.startsAt)
  const economy = createEconomy({ sequelize, models, configVersion: config.version, clock: () => now })
  const participants = createParticipants({ models, economy, event })
  const collection = createCollection({ models, participants, event, random: options.collectionRandom || (() => 0) })
  const theft = createTheft({ models, participants, collection, event, random: options.targetRandom || (() => 0), listMembers: options.listMembers || (() => members) })
  const input = key => ({ eventId: config.eventId, guildId: 'guild', actorId: 'alice', interactionId: key, action: 'trick' })
  const actions = createActions({ models, participants, economy, event, handlers: theft.handlers,
    getCurseState: () => false, random: () => options.outcomeRoll ?? 0 })
  await participants.register(input('register'))
  const row = userId => models.Participant.findOne({ where: { eventId: config.eventId, guildId: 'guild', userId } })
  const register = async (userId, values = {}) => {
    await participants.register({ ...input(`register-${userId}`), actorId: userId })
    const user = await row(userId); await user.update(values); return user
  }
  return { models, economy, participants, theft, actions, input, row, register, time: value => { now = new Date(value) } }
}
const human = (userId, extra = {}) => ({ userId, bot: false, displayName: userId, ...extra })

test('random sampling is without replacement and can select every candidate', () => {
  assert.deepEqual(randomTargets(['a','b','c','d'], 3, () => .999999), ['d','c','b'])
  for (let i = 0; i < 4; i++) assert.equal(randomTargets(['a','b','c','d'], 1, () => (i + .5) / 4)[0], ['a','b','c','d'][i])
  assert.throws(() => randomTargets(['a'], 1, () => 1), /Random value/)
})

test('nonparticipant theft materializes only chosen victim, excludes self/bots, includes admin and strips mention text', async t => {
  const f = await fixture(t, [human('alice'), human('robot', { bot: true }), human('bob', { admin: true, displayName: '<@123> @everyone' }), human('carol'), human('bob')])
  const result = await f.actions.execute(f.input('steal'))
  assert.equal(result.receipt.candySpent, 1)
  assert.equal(result.receipt.result.stolen, 1)
  assert.equal((await f.row('alice')).candy, 10)
  assert.equal((await f.row('bob')).candy, 9)
  assert.equal((await f.row('bob')).registeredAt, null)
  assert.equal(await f.row('carol'), null)
  assert.equal(await f.models.Participant.count(), 2)
  assert.equal(result.receipt.result.victims[0].registered, false)
  assert.equal(result.receipt.result.victims[0].name, '＠123 ＠everyone')
  const rows = await f.models.Ledger.findAll({ where: { operationId: 'discord:steal', resource: 'candy' } })
  assert.equal(rows.filter(row => row.relatedUserId).reduce((sum, row) => sum + row.delta, 0), 0)
})

test('heist picks random distinct funded victims and limits credit to caller capacity', async t => {
  const f = await fixture(t, ['bob','carol','dan','eve'].map(id => human(id)), { outcomeRoll: .25, targetRandom: () => .999999 })
  await (await f.row('alice')).update({ candy: 79 })
  const result = await f.actions.execute(f.input('heist'))
  assert.deepEqual(result.receipt.result.victims.map(victim => victim.userId), ['eve','dan'])
  assert.equal(result.receipt.result.stolen, 2)
  assert.equal(result.receipt.candy, 80)
  assert.equal(await f.row('bob'), null)
  await (await f.row('alice')).update({ candy: 10 })
  const full = await f.actions.execute(f.input('full-heist'))
  assert.equal(full.receipt.result.stolen, 3)
  assert.deepEqual(full.receipt.result.victims.map(victim => victim.userId), ['eve','dan','carol'])
})

test('protection lasts exactly to expiry, includes both resources and ignores another guild effects', async t => {
  const f = await fixture(t, [human('bob'), human('carol')])
  const bob = await f.register('bob', { eyes: 1 })
  const carol = await f.register('carol', { eyes: 1 })
  const other = await f.models.Participant.create({ eventId: config.eventId, guildId: 'other', userId: 'carol', refillAnchor: new Date(config.startsAt) })
  const expiresAt = new Date(Date.parse(config.startsAt) + config.protection.theftDurationMs)
  await f.models.Effect.create({ participantId: bob.id, effectType: 'theft_protection', expiresAt })
  await f.models.Effect.create({ participantId: other.id, effectType: 'theft_protection', expiresAt })
  const inspect = resource => f.economy.execute({ ...f.input(`inspect-${resource}-${Date.now()}`), operationType: 'inspect_test' }, async ctx =>
    ({ ids: (await f.theft.candidates(ctx, 'alice', resource)).map(member => member.userId) }))
  assert.deepEqual((await inspect('eyes')).receipt.ids, ['carol'])
  assert.deepEqual((await inspect('candy')).receipt.ids, ['carol'])
  f.time(expiresAt)
  assert.deepEqual((await inspect('eyes')).receipt.ids, ['bob','carol'])
  assert.equal(carol.eyes, 1)
})

test('Eye victim needs registration/funds but no activity; theft converts at five and replay does not steal twice', async t => {
  const f = await fixture(t, [human('unknown'), human('bob')], { outcomeRoll: .99 })
  await f.register('bob', { eyes: 1, lastActive: null })
  await (await f.row('alice')).update({ eyes: 4 })
  const result = await f.actions.execute(f.input('eye'))
  assert.equal(result.receipt.result.stolen, 1)
  assert.equal(result.receipt.result.found, 0)
  assert.equal(result.receipt.result.awards.length, 1)
  assert.equal((await f.row('bob')).eyes, 0)
  assert.equal((await f.row('alice')).eyes, 0)
  assert.equal(await f.row('unknown'), null)
  const replay = await f.actions.execute(f.input('eye'))
  assert.deepEqual(replay.receipt, result.receipt)
})

test('solo or protected-only Eye pool finds one; no candy target gives paid no-effect without minting candy', async t => {
  const solo = await fixture(t, [], { outcomeRoll: .99 })
  assert.equal((await solo.actions.execute(solo.input('solo'))).receipt.result.found, 1)
  const protectedOnly = await fixture(t, [human('bob')], { outcomeRoll: .99 })
  const bob = await protectedOnly.register('bob', { eyes: 1 })
  await protectedOnly.models.Effect.create({ participantId: bob.id, effectType: 'theft_protection', expiresAt: new Date(Date.parse(config.startsAt) + 3600000) })
  assert.equal((await protectedOnly.actions.execute(protectedOnly.input('protected'))).receipt.result.found, 1)
  assert.equal((await protectedOnly.row('bob')).eyes, 1)
  const candy = await fixture(t)
  const empty = await candy.actions.execute(candy.input('empty'))
  assert.equal(empty.receipt.candy, 9)
  assert.equal(empty.receipt.result.noEffect, 'no_funded_candy_target')
})

test('concurrent last-Eye theft transfers once; next action finds rather than spending a nonexistent Eye', async t => {
  const f = await fixture(t, [human('bob')], { outcomeRoll: .99 })
  await f.register('bob', { eyes: 1 })
  const results = await Promise.all([f.actions.execute(f.input('one')), f.actions.execute(f.input('two'))])
  assert.equal(results.reduce((sum, result) => sum + result.receipt.result.stolen, 0), 1)
  assert.equal(results.reduce((sum, result) => sum + result.receipt.result.found, 0), 1)
  assert.equal((await f.row('bob')).eyes, 0)
  assert.equal((await f.row('alice')).eyes, 2)
})

test('membership or RNG/award errors roll back action cost and never mint a fallback Eye', async t => {
  const broken = await fixture(t, [], { outcomeRoll: .99, listMembers: () => { throw new Error('Membership unavailable') } })
  await assert.rejects(() => broken.actions.execute(broken.input('bad')), /Membership unavailable/)
  assert.equal((await broken.row('alice')).candy, 10)
  assert.equal((await broken.row('alice')).eyes, 0)
  const award = await fixture(t, [human('bob')], { outcomeRoll: .99, collectionRandom: () => 1 })
  await award.register('bob', { eyes: 1 })
  await (await award.row('alice')).update({ eyes: 4 })
  await assert.rejects(() => award.actions.execute(award.input('award')), /Random value/)
  assert.equal((await award.row('bob')).eyes, 1)
  assert.equal((await award.row('alice')).eyes, 4)
  assert.equal((await award.row('alice')).candy, 10)
})

test('lazy funding uses due refill but an exhausted victim is skipped without extra materialization', async t => {
  const f = await fixture(t, [human('bob')])
  await f.register('bob', { candy: 0 })
  assert.equal((await f.actions.execute(f.input('empty'))).receipt.result.stolen, 0)
  f.time(new Date(Date.parse(config.startsAt) + 10800000))
  assert.equal((await f.actions.execute(f.input('refilled'))).receipt.result.stolen, 1)
  assert.equal((await f.row('bob')).candy, 9)
})
