const fs=require('fs'),cp=require('child_process'); const applied=JSON.parse(fs.readFileSync('artifacts/spooky-production-launch/storage-apply.json'));const copy=JSON.parse(fs.readFileSync('artifacts/spooky-production-launch/legacy-copy.json'));const document=`# Production launch — October 2, 2026

The human accepted live development testing, placeholders for five missing badge artworks and the current approved economy, then explicitly authorized running production from feature/S-1-spooky without merging. That remains the active branch; both PM2 processes use this checkout. No branch switch, merge, reset or agent-created commit occurred. Future source/config edits affect the live checkout: audit and reload only the intended environment. No recurring monitoring automation was requested or created.

## Data and prerequisites

The initial audit found no config/prod.sqlite and award roles above the bot. The human identified/approved the legacy source C:/Users/headm/code/sanity-bot-2/config/dev.sqlite instead of the development test copy, and moved Bots above Sweet Tooth/Scream Supreme. Fresh production role/channel/intents checks pass. Authoritative credentials come from .env.production; no credentials are printed. Production guild 1259991510410334219; app 1286400654985658368. Development guild/app/database remain distinct.

The legacy source contains 79 accounts; original file is preserved unchanged. A readonly VACUUM INTO copy was made to config/prod.sqlite, with every table's data digest and schema digest compared, integrity ok and zero foreign-key violations. Test progress/wallet alterations from config/dev.sqlite were not copied. No account, Fate or Bank resets were performed.

The explicit production-only storage entry point reuses the existing file-identity, target-isolation, reviewed SHA-256, verified backup and exclusive atomic migration transaction guards. Existing development CLI still rejects production. The production selector compares its own source against dev.sqlite (and sidecars), never itself. CLI accepts only --production with NODE_ENV=production, stopped-writer confirmation for backup/apply, no path overrides/down/restore. Synthetic regressions verify all four migrations and legacy-row/development-file preservation.

Reviewed production plan f71429140e7fd704d7c7fc7f47d49d141ef4c9ee3b9ef00856810aa2b7a69136 applied all four migrations atomically while production was stopped, with tracking/provenance committed together. Verified backup: ${applied.backupPath}. The historical backup filename dev.sqlite is only the backup's basename; its manifest binds the PRODUCTION source/target. It must not be confused with the development live database. Do not run stopped-writer apply/backup while production is online. Recovery needs reviewed stopped-writer restore; never copy development storage over production.

## Settings, emojis and commands

Global event enabled remains false; explicit productionEnabled=true and developmentEnabled=true activate only their respective runtimes. NODE_ENV=test remains disabled. Version 8/manifest 2 and economy odds/costs/refill are unchanged: initial 10, capacity 80, 1 candy/18 minutes = 80 naturally generated/day. No hard action/draw limit added. Existing two-seed population report remains diagnostic and not a guarantee of badge completion; the human chose current rules for live play.

Production-only winner settings are enabled. Combined SCREAM SUPREME role comes from selected SCREAMSUPREMEID; announcement destination is selected SERVERANNOUNCEMENTSID (1267921560203694160). Announcement is November 1, 2026 at noon Pacific, 2026-11-01T20:00:00.000Z; November 1 daylight-saving transition is accounted for. Production override cannot enable development's finale or copy its channel. Human supplied date/channel; noon is the stated implementation assumption consistent with existing reminders. Runtime still freezes winner proof at closure before delayed announcement/role delivery. Pending uncertain deliveries remain inspection-only. Weekly Unwanted reminder is active; Resident recruitment remains disabled.

Earned server emojis are now configured for Selene and Marq in both servers. Production collector roles: Selene 1555732559856668713, Marq 1555732571361517750. Development Marq role: 1555732548146036837; existing Selene access retained. Each emoji permits its collector role and the bot renderer/managed role, verified through fresh REST GET. Guild-pinned configuration prevents cross-server role reuse. Collector membership reconciles on supported actions/views, including test-reset removal; no member-join/background collector worker. Collection/leaderboard resolve spooky_marq_badge instead of the generic medal for Marq completion. Badge art is main completion image, completed token thumbnail. The remaining five badges retain accepted placeholders.

Registry reviewed hash 389330d56b63cf5cdc86a2a973a614963dfe76de3c49b52fc363ef4e02f4ee35 applied thirteen production commands; no existing command was removed. All returned definitions verified and a fresh GET matches. Existing eight production commands retained; current branch adds badges/spooky/spooky-admin plus preexisting Winter throw/slots and updates shop definition. Preserve future server-only commands by reviewing the live snapshot before any bulk replacement. Development registry remains fourteen including its server-only /game; no development registration occurred in this launch.

## Evidence and exact continuation

Evidence folder: artifacts/spooky-production-launch, ignored operational reports. legacy-copy.json binds row counts/digests; storage-plan.json/storage-apply.json include provenance/backup; production-permissions.json verifies roles/channels/intents; registry-check/apply and emoji setup reports retain live proof; source-snapshot.json binds the launch source. config/backups is ignored. Do not publish source database, backups, env files or account-level data.

The preactivation suite passed 306/306; exact final config isolation/full verification and process evidence follow below. Production logged in as sanity-bot#9046; production error log baseline 2,819,038 bytes / September 14 Pacific, development baseline 35,694 bytes / September 8. Historical error log entries are not new launch failures. No hands-on action/reset was performed on a real player by the agent.

Next: human live game observation on this unmerged branch. Fix reported defects conservatively; keep economy transactions/outbox replay and scope guards. Review production log changes and inspected uncertain queues before resending. To pause gameplay use /spooky-admin event pause paused:true reason:<reason>; resume with paused:false. For an emergency bot stop use pm2 stop SB-production, leaving both databases/backups intact. Never use reset-testing in production. Merge remains deferred until the human judges live stability; do not merge automatically. Future badge art can replace placeholders without changing ownership or seasonal inventory.
`;
fs.writeFileSync('docs/spooky-production-launch.md',document);
const note='Production launch authorized and completed from feature/S-1-spooky (unmerged). Read [production launch evidence and continuation](LINK) first; it supersedes all historical production-disabled/no-live-operations statements below. Human development acceptance and five badge placeholders accepted. Production uses a verified preserved legacy-data copy at config/prod.sqlite, four backed-up atomic migrations and thirteen reviewed commands. Selene/Marq native emoji access is configured in both servers. Explicit productionEnabled=true; test/global default stays disabled, version 8/economy unchanged. Winner announcement: November 1 noon Pacific to SERVERANNOUNCEMENTSID with SCREAMSUPREMEID. Do not migrate/replace storage with online writers, reset production, merge or switch branches. Exact next is human live observation and scoped fixes; no automatic monitoring or merge was scheduled.\n';
for(const file of ['README.md','AGENTS.md','docs/spooky-handoff.md','docs/spooky-implementation-checklist.md','docs/spooky-storage-tools.md','docs/badge-access.md','docs/spooky-development-acceptance.md']){let s=fs.readFileSync(file,'utf8');const at=s.indexOf('\n')+1;s=s.slice(0,at)+'\n'+note.replace('LINK',file.startsWith('docs/')?'spooky-production-launch.md':'docs/spooky-production-launch.md')+'\n'+s.slice(at);fs.writeFileSync(file,s);}
